# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Tips&Tricks
email: marianitadn@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Tips and tricks - now about frontend deploys, soon about everything
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://maria.github.io" # the base hostname & protocol for your site
twitter_username: MariaDana13
github_username:  maria

# Build settings
markdown: kramdown
